version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: koby-db-dev
    restart: always
    environment:
      POSTGRES_USER: koby
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: kobydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  koby-dev:
    container_name: koby-app
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./prisma:/app/prisma
    env_file:
      - .env
    depends_on:
      - postgres
    command: npm run dev

  studio:
    image: node:22-alpine
    container_name: prisma-studio
    working_dir: /app
    command: ["npx", "prisma", "studio"]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - postgres

volumes:
  postgres_data:
