version: '3.8'

services:
  koby-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koby-bot
    restart: unless-stopped
    volumes:
      # Montage des fichiers de configuration
      - ./config:/app/config:ro
      # Montage des données persistantes (logs, etc.)
      - ./data:/app/data
      # Montage du script de mise à jour
      - ./scripts:/app/scripts:ro
      # Socket Docker pour permettre les redémarrages
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NODE_ENV=production
      - TZ=Europe/Paris
    networks:
      - bot-network
    # Optionnel : pour les logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Service optionnel pour un reverse proxy si nécessaire
  # nginx:
  #   image: nginx:alpine
  #   container_name: koby-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - koby-bot
  #   networks:
  #     - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local