version: "3.9"

services:
  koby:
    container_name: koby-bot
    build:
      context: .            # <- Chemin du dépôt cloné par Portainer
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app

    # Volumes montés pour persistance des configs
    volumes:
      - ./config:/app/config
