version: "3.9"

services:
  koby:
    container_name: koby-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - ./config:/app/config